In [ ]:
!pip install ndjson

In [ ]:
import numpy as np
import ndjson
from sklearn.feature_extraction.text import CountVectorizer
from numpy.linalg import svd

In [ ]:
f = open('/content/drive/MyDrive/cran_experiment.ndjson')
file = ndjson.reader(f)
#corpus
corpus = [d['title'] for d in file]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#query to be searched
query = ['transient heat conduction into a double-layer']

In [ ]:
vectorizer = CountVectorizer()
td = vectorizer.fit_transform(corpus)

vectorizer.get_feature_names_out()  #vocabulry in ascending order

array(['000', '01', '02', ..., 'zero', 'zone', 'zoom'], dtype=object)

In [ ]:
td_mat = td.T.toarray()
print("Term-document matrix\n", td_mat)

Term-document matrix
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#SVD of the Term-Document matrix
[u,s,vt] = svd(td_mat,False)

In [ ]:
#Transforming the query into a vector
q = vectorizer.transform(query)
q = q.toarray()
print(q)

[[0 0 0 ... 0 0 0]]


In [ ]:
#Finding the new query vector
q = np.matmul(np.matmul(q,u),np.linalg.inv(np.diag(s)))
print(q)

[[-1.98927620e-03 -9.28967961e-03  9.85087716e-03 ...  3.76029641e+12
  -2.99942699e+11  5.61055170e+12]]


In [ ]:
#finding the most similar document for the query vector by taking the dot product between query and 
#each column in the vt matrix and normalize them
similarities = []
for i in range(len(vt)):
    similarities.append(list(np.dot(q,vt[:,i])/(np.linalg.norm(q)*np.linalg.norm(vt[:,i])))[0])

print('Most similar document:')
idx = similarities.index(max(similarities))
corpus[idx]