In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn import metrics
import numpy as np

 
    

def SVM(categories):
    
    twenty_train = fetch_20newsgroups(subset='train',categories=categories, shuffle=True, random_state=42)

    
    text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42))])
    _ = text_clf.fit(twenty_train.data, twenty_train.target)

    # evaluate on test set
    twenty_test = fetch_20newsgroups(subset='test',categories=categories, shuffle=True, random_state=42)
    predicted = text_clf.predict(twenty_test.data)
    print("*** SVM Model ***")
    print("Newsgroup Categories : ", categories )
    print("Accuracy : {}%".format(np.mean(predicted == twenty_test.target)*100)) 
    print(metrics.classification_report(twenty_test.target, predicted, target_names=twenty_test.target_names))
    print("Confusion Matrix : \n", metrics.confusion_matrix(twenty_test.target, predicted))

    
# selected categories
categories=['sci.med','sci.space','sci.electronics']
NBModel(categories)
SVM(categories)

SVM(categories)

*** Naive Bayes Model ***
Newsgroup Categories :  ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
Accuracy : 83.48868175765645%
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

              accuracy                           0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502

Confusion Matrix : 
 [[192   2   6 119]
 [  2 347   4  36]
 [  2  11 322  61]
 [  2   2   1 393]]
*** SVM Model ***
Newsgroup Categories :  ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
Accuracy : 91.14513981358189%
                        precision    recall  f1-score   support

           alt.atheism       0